### ISSUE TITLE
calico cluster is failing with coreos

### ISSUE THREAD

**Issue by Born2Bake** [stackhpc/magnum-terraform#1]
Hello,

First of all, I want to thank you a lot that you kept that repo up-to-date. Your work helped me a lot of deploying and use Magnum with Openstack. I am not sure if you will be able to help me with troubleshooting some stuff but:

Env details:
Openstack Train deployed via kolla-ansible

When running coreos.tfvars: 

1. Flannel cluster was deployed smoothly. Only thing: magnum-tiller metrics are failing due to:
```
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.254.0.10:53: read udp 10.100.1.2:47184->10.254.0.10:53: i/o timeout
```
```
I0405 14:10:24.439725       1 secure_serving.go:116] Serving securely on [::]:8443
E0405 14:10:58.562179       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-master-0": no metrics known for node
E0405 14:10:58.562375       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-node-0": no metrics known for node
E0405 14:11:01.755324       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-master-0": no metrics known for node
E0405 14:11:01.755353       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-node-0": no metrics known for node
E0405 14:11:24.463053       1 manager.go:111] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:k8s-flannel-coreos-ooup3hzrwji2-node-0: unable to fetch metrics from Kubelet k8s-flannel-coreos-ooup3hzrwji2-node-0 (k8s-flannel-coreos-ooup3hzrwji2-node-0): Get https://k8s-flannel-coreos-ooup3hzrwji2-node-0:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup k8s-flannel-coreos-ooup3hzrwji2-node-0 on 10.254.0.10:53: no such host, unable to fully scrape metrics from source kubelet_summary:k8s-flannel-coreos-ooup3hzrwji2-master-0: unable to fetch metrics from Kubelet k8s-flannel-coreos-ooup3hzrwji2-master-0 (k8s-flannel-coreos-ooup3hzrwji2-master-0): Get https://k8s-flannel-coreos-ooup3hzrwji2-master-0:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup k8s-flannel-coreos-ooup3hzrwji2-master-0 on 10.254.0.10:53: no such host]
```
2. Calico cluster is failing for me and the only thing I was able to figure out (heat conf):
```
+ for service in etcd docker kube-apiserver kube-controller-manager kube-scheduler kubelet kube-proxy
+ echo 'restart service kube-apiserver'
+ ssh -F /srv/magnum/.ssh/config root@localhost systemctl restart kube-apiserver
```
Kube apiserver is failing to start but when I checked it again, it started to run after 1-2min. Did you face the same issue with calico?

3. Do you know by any chance why it takes so long for fedora-atomic to boot? It takes ages before it passes NTP client/server and SSH kernel modules.

4. Is there any way to specify octavia's network id's?

Thank you very much again

**Comment by brtknr** [comment]
> Hello,
> 
> First of all, I want to thank you a lot that you kept that repo up-to-date. Your work helped me a lot of deploying and use Magnum with Openstack. I am not sure if you will be able to help me with troubleshooting some stuff but:
> 
> Env details:
> Openstack Train deployed via kolla-ansible
> 
> When running coreos.tfvars:
> 
> 1. Flannel cluster was deployed smoothly. Only thing: magnum-tiller metrics are failing due to:
> 
> ```
> Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
> Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.254.0.10:53: read udp 10.100.1.2:47184->10.254.0.10:53: i/o timeout
> ```
> 
> ```
> I0405 14:10:24.439725       1 secure_serving.go:116] Serving securely on [::]:8443
> E0405 14:10:58.562179       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-master-0": no metrics known for node
> E0405 14:10:58.562375       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-node-0": no metrics known for node
> E0405 14:11:01.755324       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-master-0": no metrics known for node
> E0405 14:11:01.755353       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-node-0": no metrics known for node
> E0405 14:11:24.463053       1 manager.go:111] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:k8s-flannel-coreos-ooup3hzrwji2-node-0: unable to fetch metrics from Kubelet k8s-flannel-coreos-ooup3hzrwji2-node-0 (k8s-flannel-coreos-ooup3hzrwji2-node-0): Get https://k8s-flannel-coreos-ooup3hzrwji2-node-0:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup k8s-flannel-coreos-ooup3hzrwji2-node-0 on 10.254.0.10:53: no such host, unable to fully scrape metrics from source kubelet_summary:k8s-flannel-coreos-ooup3hzrwji2-master-0: unable to fetch metrics from Kubelet k8s-flannel-coreos-ooup3hzrwji2-master-0 (k8s-flannel-coreos-ooup3hzrwji2-master-0): Get https://k8s-flannel-coreos-ooup3hzrwji2-master-0:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup k8s-flannel-coreos-ooup3hzrwji2-master-0 on 10.254.0.10:53: no such host]
> ```
> 
> 1. Calico cluster is failing for me and the only thing I was able to figure out (heat conf):
> 
> ```
> + for service in etcd docker kube-apiserver kube-controller-manager kube-scheduler kubelet kube-proxy
> + echo 'restart service kube-apiserver'
> + ssh -F /srv/magnum/.ssh/config root@localhost systemctl restart kube-apiserver
> ```
> 
> Kube apiserver is failing to start but when I checked it again, it started to run after 1-2min. Did you face the same issue with calico?
> 
> 1. Do you know by any chance why it takes so long for fedora-atomic to boot? It takes ages before it passes NTP client/server and SSH kernel modules.
> 2. Is there any way to specify octavia's network id's?
> 
> Thank you very much again

**Comment by brtknr** [comment]
> Hello,
> 
> First of all, I want to thank you a lot that you kept that repo up-to-date. Your work helped me a lot of deploying and use Magnum with Openstack. I am not sure if you will be able to help me with troubleshooting some stuff but:
> 
> Env details:
> Openstack Train deployed via kolla-ansible
> 

 Hi @Born2Bake, I have mainly only tested this on master branch and latest stable/train and have not come across the issues you have described. I have not tested this against older release so please do so at your own peril :)

> When running coreos.tfvars:
> 
> 1. Flannel cluster was deployed smoothly. Only thing: magnum-tiller metrics are failing due to:
> 
> ```
> Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
> Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.254.0.10:53: read udp 10.100.1.2:47184->10.254.0.10:53: i/o timeout
> ```

Is this consistently the case?

> 
> ```
> I0405 14:10:24.439725       1 secure_serving.go:116] Serving securely on [::]:8443
> E0405 14:10:58.562179       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-master-0": no metrics known for node
> E0405 14:10:58.562375       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-node-0": no metrics known for node
> E0405 14:11:01.755324       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-master-0": no metrics known for node
> E0405 14:11:01.755353       1 reststorage.go:135] unable to fetch node metrics for node "k8s-flannel-coreos-ooup3hzrwji2-node-0": no metrics known for node
> E0405 14:11:24.463053       1 manager.go:111] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:k8s-flannel-coreos-ooup3hzrwji2-node-0: unable to fetch metrics from Kubelet k8s-flannel-coreos-ooup3hzrwji2-node-0 (k8s-flannel-coreos-ooup3hzrwji2-node-0): Get https://k8s-flannel-coreos-ooup3hzrwji2-node-0:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup k8s-flannel-coreos-ooup3hzrwji2-node-0 on 10.254.0.10:53: no such host, unable to fully scrape metrics from source kubelet_summary:k8s-flannel-coreos-ooup3hzrwji2-master-0: unable to fetch metrics from Kubelet k8s-flannel-coreos-ooup3hzrwji2-master-0 (k8s-flannel-coreos-ooup3hzrwji2-master-0): Get https://k8s-flannel-coreos-ooup3hzrwji2-master-0:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup k8s-flannel-coreos-ooup3hzrwji2-master-0 on 10.254.0.10:53: no such host]
> ```
> 
> 1. Calico cluster is failing for me and the only thing I was able to figure out (heat conf):
> 
> ```
> + for service in etcd docker kube-apiserver kube-controller-manager kube-scheduler kubelet kube-proxy
> + echo 'restart service kube-apiserver'
> + ssh -F /srv/magnum/.ssh/config root@localhost systemctl restart kube-apiserver
> ```
> 
> Kube apiserver is failing to start but when I checked it again, it started to run after 1-2min. Did you face the same issue with calico?

Sounds like you are not running the latest release of Magnum train. We have a fix for TimeoutRestartSec which addresses this issue.

> 
> 1. Do you know by any chance why it takes so long for fedora-atomic to boot? It takes ages before it passes NTP client/server and SSH kernel modules.

Do you have nested virt enabled on your VMs? I have encountered slowness when it has been disabled. Also did you take a look at upload-atomic.sh script? There is a hardware randng flag you need to supply otherwise the VM runs out of entropy which could be why you are experience slowness.

> 2. Is there any way to specify octavia's network id's

I don't think there is a way to do this that I am aware of.

> 
> Thank you very much again

**Comment by Born2Bake** [comment]
Hi,

> Is this consistently the case?

Nope, sometimes when I create cluster there is no issues with metrics. I am not really sure why its failing sometimes.

> Sounds like you are not running the latest release of Magnum train. We have a fix for TimeoutRestartSec which addresses this issue.

I am running kolla-ansible:train version, magnum version: 9.2.0. TimeoutRestartSec - can I add that too in your terraform scripts?

> Do you have nested virt enabled on your VMs? I have encountered slowness when it has been disabled. Also did you take a look at upload-atomic.sh script? There is a hardware randng flag you need to supply otherwise the VM runs out of entropy which could be why you are experience slowness.

Yes, I ve added atomic using your bash script. The only way I can overcome that slowness if I go to instance console and press "enter" many times so it can pass through NTP and SSH key gen phase.

Although, I was testing cluster autoscaling, magnum-healing. I assume you were testing them in DevStack, however, they are crashing all the time for my kolla-ansible stack. If I use 17.4 version its crashing, if I use 15.7 version it creates nodes when scaling but neither autoscaler,autohealer,cloud-manager cant register those and scale up/down the cluster. 

Thank you

**Comment by brtknr** [comment]
Please try again with 9.4.0 release due out soon and reopen if still an issue as I cannot reproduce.
